import { readFile, writeFile, mkdir } from "node:fs/promises";
import subsetFont from "subset-font";

const FAMILIES = [
  { file: "Dosis[wght].ttf", family: "Dosis", out: "dosis", weight: "200 800" },
  { file: "Quicksand[wght].ttf", family: "Quicksand", out: "quicksand", weight: "300 700" },
  { file: "Jura[wght].ttf", family: "Jura", out: "jura", weight: "300 700" },
  { file: "JetBrainsMono[wght].ttf", family: "JetBrains Mono", out: "jetbrains-mono", weight: "100 800" },
];

const UNICODE_RANGE =
  "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, " +
  "U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, " +
  "U+2193, U+2212, U+2215, U+FEFF, U+FFFD";

function subsetCharacters() {
  const ranges = [
    [0x0020, 0x00ff],
    [0x0131, 0x0131],
    [0x0152, 0x0153],
    [0x02bb, 0x02bc],
    [0x02c6, 0x02c6],
    [0x02da, 0x02da],
    [0x02dc, 0x02dc],
    [0x0304, 0x0304],
    [0x0308, 0x0308],
    [0x0329, 0x0329],
    [0x2000, 0x206f],
    [0x2074, 0x2074],
    [0x20ac, 0x20ac],
    [0x2122, 0x2122],
    [0x2191, 0x2191],
    [0x2193, 0x2193],
    [0x2212, 0x2212],
    [0x2215, 0x2215],
    [0xfffd, 0xfffd],
  ];

  let out = "";
  for (const [start, end] of ranges) {
    for (let cp = start; cp <= end; cp++) out += String.fromCodePoint(cp);
  }
  return out;
}

await mkdir("assets/fonts", { recursive: true });

const characters = subsetCharacters();
const faces = [];
let originalTotal = 0;
let subsetTotal = 0;

for (const { file, family, out, weight } of FAMILIES) {
  const original = await readFile(`dev/fonts/${file}`);

  const subset = await subsetFont(original, characters, { targetFormat: "woff2" });

  await writeFile(`assets/fonts/${out}.woff2`, subset);

  originalTotal += original.length;
  subsetTotal += subset.length;

  faces.push(
    `@font-face {\n` +
      `  font-family: "${family}";\n` +
      `  src: url("/assets/fonts/${out}.woff2") format("woff2-variations");\n` +
      `  font-weight: ${weight};\n` +
      `  font-style: normal;\n` +
      `  font-display: swap;\n` +
      `  unicode-range: ${UNICODE_RANGE};\n` +
      `}`
  );

  const pct = Math.round((1 - subset.length / original.length) * 100);
  console.log(
    `${family.padEnd(16)} ${String(original.length).padStart(7)} -> ${String(subset.length).padStart(6)} bytes  (-${pct}%)`
  );
}

await writeFile(
  "dev/css/fonts.generated.css",
  `/* Generated by scripts/fonts.mjs. Do not edit; run \`npm run build:fonts\`. */\n\n` +
    faces.join("\n\n") +
    "\n"
);

const pct = Math.round((1 - subsetTotal / originalTotal) * 100);
console.log(`\ntotal            ${originalTotal} -> ${subsetTotal} bytes  (-${pct}%)`);
