import { writeFile } from "node:fs/promises";

const LUCIDE = "https://cdn.jsdelivr.net/npm/lucide-static@latest/icons";
const SIMPLE = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons";

const UI = [
  "house",
  "user-round",
  "mail",
  "newspaper",
  "boxes",
  "images",
  "file-text",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "panel-left-close",
  "panel-left-open",
  "menu",
  "sun",
  "moon",
  "search",
  "arrow-up",
  "x",
  "copy",
  "check",
  "link",
  "calendar",
  "tag",
  "tags",
  "rss",
  "external-link",
  "send",
  "info",
  "triangle-alert",
  "circle-alert",
  "lightbulb",
];

const BRANDS = [
  { name: "github" },
  { name: "linkedin" },
  { name: "x", id: "twitter" },
  { name: "facebook" },
  { name: "youtube" },
];

function innerSvg(markup) {
  const open = markup.indexOf(">", markup.indexOf("<svg"));
  const close = markup.lastIndexOf("</svg>");
  return markup
    .slice(open + 1, close)
    .replace(/<title>.*?<\/title>/gs, "")
    .replace(/\s+/g, " ")
    .trim();
}

async function fetchIcon(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.text();
}

const symbols = [];
const failures = [];

for (const name of UI) {
  try {
    const body = innerSvg(await fetchIcon(`${LUCIDE}/${name}.svg`));
    symbols.push(
      `  <symbol id="icon-${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" ` +
        `stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${body}</symbol>`
    );
  } catch (err) {
    failures.push(`lucide/${name}: ${err.message}`);
  }
}

for (const { name, id } of BRANDS) {
  try {
    const body = innerSvg(await fetchIcon(`${SIMPLE}/${name}.svg`));
    symbols.push(
      `  <symbol id="icon-${id ?? name}" viewBox="0 0 24 24" fill="currentColor">${body}</symbol>`
    );
  } catch (err) {
    failures.push(`simple-icons/${name}: ${err.message}`);
  }
}

if (failures.length) {
  console.error("Failed to fetch:\n  " + failures.join("\n  "));
  process.exitCode = 1;
}

await writeFile(
  "_includes/icons.html",
  `<!-- Generated by scripts/icons.mjs. Do not edit; run \`npm run build:icons\`. -->\n` +
    `<!-- UI icons: Lucide (ISC). Brand marks: Simple Icons (CC0). -->\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" hidden aria-hidden="true">\n` +
    symbols.join("\n") +
    `\n</svg>\n`
);

console.log(`Wrote _includes/icons.html with ${symbols.length} symbols.`);
