import { initTheme } from "./modules/theme.js";
import { initSidebar } from "./modules/sidebar.js";
import { initFooterYear, initAliveTime, initBackToTop } from "./modules/chrome.js";
import { initJoshuaProject } from "./modules/joshua-project.js";
import { initNewsletter } from "./modules/newsletter.js";
import { initContactForm } from "./modules/contact.js";
import { initLightbox } from "./modules/lightbox.js";
import { initCodeCopy } from "./modules/code-copy.js";
import { initHeadingAnchors } from "./modules/headings.js";
import { initReadingProgress } from "./modules/reading-progress.js";
import { initSearchPage, initSearchShortcut } from "./modules/search.js";

initTheme();
initSidebar();
initFooterYear();
initAliveTime();
initBackToTop();
initJoshuaProject();
initNewsletter();
initContactForm();
initLightbox();
initCodeCopy();
initHeadingAnchors();
initReadingProgress();
initSearchPage();
initSearchShortcut();
